name: Docker Guacamole Server Build
  
on:
  workflow_dispatch:

jobs:
  guacamole_server:
    name: Build guacamole-server
    runs-on: ubuntu-latest
    steps:
      - name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Get resources
        run: |
          rm -rf *
          wget -O /tmp/master.zip https://github.com/apache/guacamole-server/archive/refs/heads/master.zip
          unzip /tmp/master.zip -d /tmp
          mv /tmp/guacamole-server-master/* .
          
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/guacamole-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/guacamole-server:1.4.0
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/guacamole-server:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/guacamole-server:cache,mode=max
